chat:
  context: default
  greedy_mode: false
  logs_dir: /home/ali/.local/share/instructlab/chatlogs
  max_tokens:
  model: /home/ali/.cache/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf
  session:
  vi_mode: false
  visible_overflow: true
serve:
  backend:
  chat_template:
  host_port: 127.0.0.1:8000
  llama_cpp:
    gpu_layers: -1
    llm_family: ''
    max_ctx_size: 4096
  model_path: /home/ali/.cache/instructlab/models/merlinite-7b-lab-Q4_K_M.gguf
  vllm:
    gpus:
    llm_family: ''
    max_startup_attempts: 120
    vllm_args: []
