# SPDX-License-Identifier: Apache-2.0

name: Build Docs Website

on:
  push:
    branches:
      - "main"
      - "release-**"
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'
      - '.github/workflows/build-docs.yml' # This workflow
  pull_request:
    branches:
      - "main"
      - "release-**"
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'
      - '.github/workflows/build-docs.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  test-workflow-ready:
    permissions:
      checks: read
    uses: ./.github/workflows/status-checks.yml
    with:
      job_ids: >- # Space-separated job ids to wait on for status checks
        DCO
        actionlint
        markdown-lint
        shellcheck
        spellcheck
        lint-workflow-complete
  docs:
    runs-on: ubuntu-latest
    needs: ["test-workflow-ready"]
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          # https://github.com/actions/checkout/issues/249
          fetch-depth: 0

      - name: Setup Python 3.11
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/requirements*.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: Run tox docs target
        run: |
          make docs
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
  test-workflow-complete:
    permissions:
      checks: read
    uses: ./.github/workflows/status-checks.yml
    with:
      job_ids: >- # Space-separated job ids to wait on for status checks
        test-workflow-ready
        docs
