# SPDX-License-Identifier: Apache-2.0

name: Build Docs Website

on:
  push:
    branches:
      - "main"
      - "release-**"
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'
      - '.github/workflows/build-docs.yml' # This workflow
  pull_request:
    branches:
      - "main"
      - "release-**"
    paths:
      - '**/*.md'
      - '.markdownlint-cli2.yaml'
      - '.github/workflows/build-docs.yml' # This workflow

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: _build/
          force_orphan: true
